### PR TITLE
fix(geosearch): prevent focus from getting stuck in geosearch

### LINKED ISSUE #3784: Geosearch keyboard navigation
When I use the keyboard to with Geosearch, navigation get stuck inside the panel. If you enter e.g. Toronto inside the text field then tab to the result to enter the result panel, there is no way to get out. The esc key that use to work in 2.5 doesn't work anymore. At the same time, tab order is not good compare to 2.5.

```
angular.js:15536 TypeError: o.closePanelFromHistory is not a function
    at shell.directive.js:76
    at u.$eval (angular.js:19356)
    at u.$apply (angular.js:19455)
    at HTMLDivElement.<anonymous> (shell.directive.js:75)
    at HTMLDivElement.dispatch (event.js:353)
    at HTMLDivElement.b.handle (event.js:160)
(anonymous) @ angular.js:15536
(anonymous) @ angular.js:11815
$apply @ angular.js:19460
(anonymous) @ shell.directive.js:75
dispatch @ event.js:353
b.handle @ event.js:160
```

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
## Description
Closes #3784 

Pressing the `esc` key will act in a manner similar to how it did in RAMP 2.5.

### Checklist

- [ ] works in IE11
- [ ] works in Edge
- [ ] works with projection change
- [ ] works with language change
- [ ] works via config file
- [ ] works via wizard
- [ ] works via API
- [ ] works via RCS
- [ ] works via bookmark load
- [ ] works in auto-legend
- [ ] works in structured legend
- [ ] works on layer reload
- [ ] datagrid works
- [ ] identify works
- [ ] the [accessibility guidelines](http://fgpv-vpgf.github.io/fgpv-vpgf/master/#/developer/accessibility_guidelines) have been respected

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated
- [x] original issue has been reviewed & updated to reflect the PR content

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3788)

### CODE REVIEW

**Comment by glitch-again** [comment]
Hey, I updated your PR Demo:

| Dev Builds                      | Prod Builds                     |
| ------------------------------- | ------------------------------- |
| [index-one.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-geosearch-accessibility/dev/samples/index-one.html)    | [index-one.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-geosearch-accessibility/prod/samples/index-one.html)    |
| [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-geosearch-accessibility/dev/samples/index-mobile.html)    | [index-mobile.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-geosearch-accessibility/prod/samples/index-mobile.html)    |
| [index-samples.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-geosearch-accessibility/dev/samples/index-samples.html)    | [index-samples.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-geosearch-accessibility/prod/samples/index-samples.html)    |
| [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-geosearch-accessibility/dev/samples/index-fgp-en.html) | [index-fgp-en.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-geosearch-accessibility/prod/samples/index-fgp-en.html) |
| [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-geosearch-accessibility/dev/samples/index-fgp-fr.html) | [index-fgp-fr.html](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-geosearch-accessibility/prod/samples/index-fgp-fr.html) |

Is it working as expected?

**Comment by RyanCoulsonCA** [comment]
A working test link can be found [here](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-geosearch-accessibility/dist/samples/index-samples.html).
