### ISSUE TITLE
SVG-based elements are not rendered in Safari on iPhone

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2187]
![](https://i.imgur.com/61wU92V.png)

Looking at the page source, md-icon elements are not added to the page at all.

Everything works correctly on desktop Safari.

**Comment by AleksueiR** [comment]
Works in 1.7.0:
![](https://i.imgur.com/CtNxpp3.png)

**Comment by AleksueiR** [comment]
Fullscreen library fails with and causes all icons to fail:
> rv-main.js:86176 undefined is not a function (evaluating '_screenfull2.default.onchange(function () {
        return toggle(true);
    })')
http://fgpv.cloudapp.net/demo/develop/dev/rv-main.js:194466

**Comment by AleksueiR** [comment]
Safari iOS doesn't support full screen at all, that's why it fails. Will need to check more carefull for support of this feature.
